esphome:
  name: "zehnder-comfo-d"
  friendly_name: "Zehnder Comfo D"
  includes:
    # - uart_proxy.h
    # - constants.h
    # - comfod.h

external_components:
  - source:
      type: git
      url: https://github.com/brechtvhb/zehnder-to-esphome
    components: [comfod]

esp32:
  board: lolin_d32_pro
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "ZUyvMHVGzJi68SJ08an99aqd0K3175eOysqGlNlp740="

ota:
  - platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "zehner-comfo-d-5De484"
    password: "Nez2kNzpFx1K"

captive_portal:

# esp32_ble_tracker:
#   scan_parameters:
#     active: True # Whether to send scan-request packets to devices to gather more info (like devicename)
#     interval: 320ms # suggested 211ms # default 320ms
#     window:   300ms # suggested 120ms # default 30ms

uart:
  - id: uart_comfod
    baud_rate: 9600
    tx_pin: 23
    rx_pin: 22
    # debug:
    #   direction: BOTH
  - id: uart_comfosense
    baud_rate: 9600
    tx_pin: 19
    rx_pin: 18
    # debug:
    #   direction: BOTH

one_wire:
  - platform: gpio
    pin: GPIO21

sensor:
  - platform: dallas_temp
    address: 0x9f08225398441428
    name: "Temperature"

binary_sensor:

comfod:
  name: "Zehnder Comfo D"
  id: "zehnder_comfo_d"
  uart_comfod: "uart_comfod"
  uart_comfosense: "uart_comfosense"
  fan_supply_air_percentage:
    name: "fan_supply_air_percentage"
  fan_exhaust_air_percentage:
    name: "fan_exhaust_air_percentage"
  fan_speed_supply:
    name: "fan_speed_supply"
  fan_speed_exhaust:
    name: "fan_speed_exhaust"
  is_bypass_valve_open:
    name: "is_bypass_valve_open"
  is_preheating:
    name: "is_preheating"
  outside_air_temperature:
    name: "outside_air_temperature"
  supply_air_temperature:
    name: "supply_air_temperature"
  return_air_temperature:
    name: "return_air_temperature"
  exhaust_air_temperature:
    name: "exhaust_air_temperature"
  enthalpy_temperature:
    name: "enthalpy_temperature"
  ewt_temperature:
    name: "ewt_temperature"
  reheating_temperature:
    name: "reheating_temperature"
  kitchen_hood_temperature:
    name: "kitchen_hood_temperature"
  return_air_level:
    name: "return_air_level"
  supply_air_level:
    name: "supply_air_level"
  is_supply_fan_active:
    name: "is_supply_fan_active"
  is_filter_full:
    name: "is_filter_full"
  is_summer_mode:
    name: "is_summer_mode"
  reheating_target_temperature:
    name: "reheating_target_temperature"
  kitchen_hood_speed_up_percentage:
    name: "kitchen_hood_speed_up_percentage"

button:
  - platform: template
    name: "Reset Filter"
    on_press:
      then:
        - lambda: |-
                id(zehnder_comfo_d)->reset_filter();

number:
  - platform: template
    name: "EWT low temperature"
    min_value: 0
    max_value: 15
    step: 0.5
    mode : slider
    lambda: |-
      return id(zehnder_comfo_d)->ewt_low_temperature->state;
    set_action:
      then:
        - lambda: |-
            id(zehnder_comfo_d)->set_ewt_low_temperature_value(x);
  - platform: template
    name: "EWT high temperature"
    min_value: 10
    max_value: 25
    step: 0.5
    mode : slider
    lambda: |-
      return id(zehnder_comfo_d)->ewt_high_temperature->state;
    set_action:
      then:
        - lambda: |-
            id(zehnder_comfo_d)->set_ewt_high_temperature_value(x);
  - platform: template
    name: "EWT speed up percentage"
    min_value: 0
    max_value: 99
    step: 1
    mode : slider
    lambda: |-
      return id(zehnder_comfo_d)->ewt_speed_up_percentage->state;
    set_action:
      then:
        - lambda: |-
            id(zehnder_comfo_d)->set_ewt_speed_up_percentage_value(x);